# Generated by Django 6.0 on 2025-12-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fqa',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
